databases:
  - name: postgres
    ipAllowList: []
    databaseName: timly_stimulus_production
    user: timly_stimulus

services:
  - type: web
    name: timly_stimulus
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bin/dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false